// This file was generated by RedwoodJS
import * as Cell from './EditPostCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditPostById, EditPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditPostCell'

type CellInputs = CellProps<SuccessType, EditPostById, typeof Cell, EditPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
